query Correrias (
  $Numero: String
  $Fecha: String
  $EnteId: Int
  $ProduccionId: Int
  $RecprodcomId: Int
) {
  Correrias (
    Numero: $Numero
    Fecha: $Fecha
    EnteId: $EnteId
    ProduccionId: $ProduccionId
    RecprodcomId: $RecprodcomId
  ){
    Id
    Numero
    Fecha
    EnteId
    ProduccionId
    RecprodcomId
    Ente {
      Id
      TipoDocumento
      NumeroDocumento
      Nombre
      Ciudad
      Direccion
      Telefono
    }
    Produccion {
      Id
      Fecha
      Lote
      Cantidad
      Despachado
      Producto {
        Id
        Nombre
        UnidadDeMedida
      }
      FechaFabricacion
      FechaVencimiento
      Envase {
        Id
        Numero
        Capacidad
        Propietario {
          Id
          Nombre
        }
      }
    }
    Recprodcom {
      Id
      Fecha
      Lote
      Cantidad
      Despachado
      Producto {
        Id
        Nombre
        UnidadDeMedida
      }
      FechaFabricacion
      FechaVencimiento
      Envase {
        Id
        Numero
        Capacidad
        Propietario {
          Id
          Nombre
        }
      }
    }
  }
}
