mutation CreateRemisionProveedor (
  $Numero: String
  $Fecha: String
  $EnteId: Int
  $EnvaseEntraId: Int
  $EnvaseSaleId: Int
  $VendedorId: Int
) {
  CreateRemisionProveedor (
    Numero: $Numero
    Fecha: $Fecha
    EnteId: $EnteId
    EnvaseEntraId: $EnvaseEntraId
    EnvaseSaleId: $EnvaseSaleId
    VendedorId: $VendedorId
  ){
    Id
    Numero
    Fecha
    EnteId
    ProduccionId
    RecprodcomId
    EnvaseEntraId
    EnvaseSaleId
    Total
    Tipo
    VendedorId
    Ente {
      Id
      TipoDocumento
      NumeroDocumento
      Nombre
      Ciudad
      Direccion
      Telefono
    }
    Produccion {
      Id
      Fecha
      Lote
      Cantidad
      Producto {
        Id
        Nombre
        UnidadDeMedida
      }
      FechaFabricacion
      FechaVencimiento
      Envase {
        Id
        Numero
        Capacidad
      }
    }
    Recprodcom {
      Id
      Fecha
      Lote
      Cantidad
      Producto {
        Id
        Nombre
        UnidadDeMedida
      }
      FechaFabricacion
      FechaVencimiento
      Envase {
        Id
        Numero
        Capacidad
      }
    }
    EnvaseEntra {
      Id
      Numero
      Capacidad
      Producto {
        Nombre
        UnidadDeMedida
      }
    }
    EnvaseSale {
      Id
      Numero
      Capacidad
      Producto {
        Nombre
        UnidadDeMedida
      }
    }
    Vendedor {
      Id
      TipoDocumento
      NumeroDocumento
      Nombre
      Ciudad
      Direccion
      Telefono
    }
  }
}
