mutation CreateRemision (
  $Numero: String
  $Fecha: String
  $EnteId: Int
  $ProduccionId: Int
  $EnvaseProduccionId: Int
  $RecprodcomId: Int
  $EnvaseRecprodcomId: Int
  $EnvaseEntraId: Int
  $Total: Float
  $VendedorId: Int
) {
  CreateRemision (
    Numero: $Numero
    Fecha: $Fecha
    EnteId: $EnteId
    ProduccionId: $ProduccionId
    EnvaseProduccionId: $EnvaseProduccionId
    RecprodcomId: $RecprodcomId
    EnvaseRecprodcomId: $EnvaseRecprodcomId
    EnvaseEntraId: $EnvaseEntraId
    Total: $Total
    VendedorId: $VendedorId
  ){
    Id
    Numero
    Fecha
    EnteId
    ProduccionId
    RecprodcomId
    EnvaseEntraId
    EnvaseSaleId
    Total
    Tipo
    VendedorId
    Ente {
      Id
      TipoDocumento
      NumeroDocumento
      Nombre
      Ciudad
      Direccion
      Telefono
    }
    Produccion {
      Id
      Fecha
      Lote
      Cantidad
      Producto {
        Id
        Nombre
        UnidadDeMedida
      }
      FechaFabricacion
      FechaVencimiento
      Envase {
        Id
        Numero
        Capacidad
      }
    }
    Recprodcom {
      Id
      Fecha
      Lote
      Cantidad
      Producto {
        Id
        Nombre
        UnidadDeMedida
      }
      FechaFabricacion
      FechaVencimiento
      Envase {
        Id
        Numero
        Capacidad
      }
    }
    EnvaseEntra {
      Id
      Numero
      Capacidad
      Producto {
        Nombre
        UnidadDeMedida
      }
    }
    EnvaseSale {
      Id
      Numero
      Capacidad
      Producto {
        Nombre
        UnidadDeMedida
      }
    }
    Vendedor {
      Id
      TipoDocumento
      NumeroDocumento
      Nombre
      Ciudad
      Direccion
      Telefono
    }
  }
}
