mutation DeleteRemision (
  $Id: Int
  $Numero: String
  $ProduccionId: Int
  $EnvaseProduccionId: Int
  $RecprodcomId: Int
  $EnvaseRecprodcomId: Int
  $EnvaseId: Int
) {
  DeleteRemision (
    Id: $Id
    Numero: $Numero
    ProduccionId: $ProduccionId
    EnvaseProduccionId: $EnvaseProduccionId
    RecprodcomId: $RecprodcomId
    EnvaseRecprodcomId: $EnvaseRecprodcomId
    EnvaseId: $EnvaseId
  ){
    Id
  }
}
