mutation DeleteProduccion ( 
  $Orden: String!,
  $EnvaseId: Int!
) {
  DeleteProduccion (
    Orden: $Orden,
    EnvaseId: $EnvaseId
  ){
    Id
    Orden
    Turno
    Fecha
    Lote
    FechaInicial
    FechaFinal
    HoraInicial
    HoraFinal
    FechaFabricacion
    FechaVencimiento
    Cantidad
    ProductoId
    EnvaseId
    PurezaFinal
    PresionFinal
    Observacion
    Envase {
      Id
      Numero
      Capacidad
    }
    Producto {
      Id
      Nombre
      UnidadDeMedida
    }
  }
}
