query Entes(
  $NumeroDocumento: String
  $Ciudad: String
  $NombreDocumento: String
  $Relacion: String
) {
  Entes(
    NumeroDocumento: $NumeroDocumento
    Ciudad: $Ciudad
    NombreDocumento: $NombreDocumento
    Relacion: $Relacion
  ) {
    Id
    TipoDocumento
    NumeroDocumento
    Nombre
    Ciudad
    Direccion
    Telefono
    Relacion
  }
}
