query Entes($NombreDocumento: String) {
  Entes(
    NombreDocumento: $NombreDocumento
  ) {
    Id
    TipoDocumento
    NumeroDocumento
    Nombre
    Ciudad
    Direccion
    Telefono
    Relacion
  }
}
