query Envases {
  Envases {
    Id
    Estado
    EnteId
    Material
    Capacidad
    ClaseProducto
    Numero
    NumeroInterno
    Presion
    AlturaConValvula
    PesoConValvula
    Valvula
    TipoValvula
    AcabadoColor
    NormaTecnicaFabricacion
    Proveedor
    FechaCompra
    Garantia
    FechaFabricacion
    PruebaHidrostatica
    EquipoAlquilado
    FechaAlquiler
    Observaciones
    Propietario {
      Id
      TipoDocumento
      NumeroDocumento
      Nombre
      Direccion
      Telefono
    }
  }
}


