query Envases (
  $Numero: String
  $NombreProducto: String
) {
  EnvasesByProducto (
    Numero: $Numero
    NombreProducto: $NombreProducto
  ){
    Id
    Estado
    EnteId
    Material
    ProductoId
    Capacidad
    Numero
    NumeroInterno
    Presion
    AlturaConValvula
    PesoConValvula
    Valvula
    TipoValvula
    AcabadoColor
    NormaTecnicaFabricacion
    Proveedor
    FechaCompra
    Garantia
    FechaFabricacion
    PruebaHidrostatica
    EquipoAlquilado
    FechaAlquiler
    Observaciones
    Disponible
    Propietario {
      Id
      TipoDocumento
      NumeroDocumento
      Nombre
      Direccion
      Telefono
    }
    Producto {
      Id
      Nombre
      UnidadDeMedida
    }
  }
}
