query Envases(
  $Numero: String
  $EnteId: Int
  $ProductoId: Int
) {
  Envases (
    Numero: $Numero
    EnteId: $EnteId
    ProductoId: $ProductoId
  ){
    Id
    Estado
    EnteId
    Material
    ProductoId
    Capacidad
    Numero
    NumeroInterno
    Presion
    AlturaConValvula
    PesoConValvula
    Valvula
    TipoValvula
    AcabadoColor
    NormaTecnicaFabricacion
    Proveedor
    FechaCompra
    Garantia
    FechaFabricacion
    PruebaHidrostatica
    EquipoAlquilado
    FechaAlquiler
    Observaciones
    Disponible
    Propietario {
      Id
      TipoDocumento
      NumeroDocumento
      Nombre
      Direccion
      Telefono
    }
    Producto {
      Id
      Nombre
      UnidadDeMedida
    }
  }
}
