query Produccions (
  $Orden: String,
  $Turno: String,
  $Fecha: String,
  $Lote: String,
  $FechaInicial: String,
  $FechaFinal: String,
  $HoraInicial: String,
  $HoraFinal: String,
  $FechaFabricacion: String,
  $FechaVencimiento: String,
  $Cantidad: Float,
  $ProductoId: Int,
  $EnvaseId: Int,
  $PurezaFinal: Float,
  $PresionFinal: Float
  $Observacion: String
) {
  Produccions (
    Orden: $Orden,
    Turno: $Turno,
    Fecha: $Fecha,
    Lote: $Lote,
    FechaInicial: $FechaInicial,
    FechaFinal: $FechaFinal,
    HoraInicial: $HoraInicial,
    HoraFinal: $HoraFinal,
    FechaFabricacion: $FechaFabricacion,
    FechaVencimiento: $FechaVencimiento,
    Cantidad: $Cantidad,
    ProductoId: $ProductoId,
    EnvaseId: $EnvaseId,
    PurezaFinal: $PurezaFinal,
    PresionFinal: $PresionFinal,
    Observacion: $Observacion
  ){
    Id
    Orden
    Turno
    Fecha
    Lote
    FechaInicial
    FechaFinal
    HoraInicial
    HoraFinal
    FechaFabricacion
    FechaVencimiento
    Cantidad
    ProductoId
    EnvaseId
    PurezaFinal
    PresionFinal
    Observacion
    Despachado
    Envase {
      Id
      Numero
      Capacidad
    }
    Producto {
      Id
      Nombre
      UnidadDeMedida
    }
  }
}
