mutation UpdateRemision (
  $Id: Int!
  $EnteId: Int
  $ProduccionId: Int
  $RecprodcomId: Int
  $EnvaseId: Int
  $Total: Float
) {
  UpdateRemision (
    Id: $Id
    EnteId: $EnteId
    ProduccionId: $ProduccionId
    RecprodcomId: $RecprodcomId
    EnvaseId: $EnvaseId
    Total: $Total
  ){
    Id
    Numero
    Fecha
    EnteId
    ProduccionId
    RecprodcomId
    EnvaseId
    Total
    Ente {
      Id
      TipoDocumento
      NumeroDocumento
      Nombre
      Ciudad
      Direccion
      Telefono
    }
    Produccion {
      Id
      Fecha
      Lote
      Cantidad
      Producto {
        Id
        Nombre
        UnidadDeMedida
      }
      FechaFabricacion
      FechaVencimiento
      Envase {
        Id
        Numero
        Capacidad
      }
    }
    Recprodcom {
      Id
      Fecha
      Lote
      Cantidad
      Producto {
        Id
        Nombre
        UnidadDeMedida
      }
      FechaFabricacion
      FechaVencimiento
      Envase {
        Id
        Numero
        Capacidad
      }
    }
    Envase {
      Id
      Numero
    }
  }
}
