mutation UpdateOneRecprodcom (
  $Id: Int
  $Cantidad: Float
  $EnvaseId: Int
  $Despachado: String
) {
  UpdateOneRecprodcom (
    Id: $Id
    Cantidad: $Cantidad
    EnvaseId: $EnvaseId
    Despachado: $Despachado
  ){
    Id
    Numero
    Fecha
    Lote
    FechaFabricacion
    FechaVencimiento
    Cantidad
    EnteId
    ProductoId
    EnvaseId
    PurezaFinal
    PresionFinal
    Certificado
    RegistroSanitario
    Otros
    Observacion
    Despachado
    Proveedor {
      Id
      TipoDocumento
      NumeroDocumento
      Nombre
      Ciudad
      Direccion
      Telefono
    }
    Envase {
      Id
      Numero
      Capacidad
      Propietario {
        Id
        TipoDocumento
        NumeroDocumento
        Nombre
        Direccion
        Telefono
      }
    }
    Producto {
      Id
      Nombre
      UnidadDeMedida
    }
  }
}
