mutation UserAddGroup(
  $UserId: Int,
  $GroupId: Int,
) {
  UserAddGroup(
    UserId: $UserId,
    GroupId: $GroupId,
  ) {
    Id
    UserName
    Password
    Active
    Groups {
      Id
      Name
    }
  }
}
