CREATE TABLE IF NOT EXISTS "User" (
  "Id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "UserName" TEXT UNIQUE,
  "Password" TEXT
);

CREATE TABLE IF NOT EXISTS "Person" (
  "UserId" INTEGER REFERENCES "User"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "Email" TEXT UNIQUE,
  "FirstName" TEXT,
  "LastName" TEXT
);

CREATE TABLE IF NOT EXISTS "Post" (
  "PersonId" INTEGER REFERENCES "Person"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "Title" TEXT,
  "Content" TEXT
);

